---
title: "Final_Project_Code"
date: now
author: "Elliot Kunz, Andrea Pareja, Anson Wu, Caroline Ritchey"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

## PC 3

```{r setup}
library(tidyverse)
library(gt)
```

```{r}
data1 <- read_csv("hapiscore_whr.csv", show_col_types = F)
data2 <- read_csv("mincpcap_cppp.csv", show_col_types = F)



clean_data1 <- data1 %>% 
  pivot_longer(cols = `2005`:`2023`,
              names_to = "year",
              values_to = "happiness")
  


clean_data2 <- data2 %>% 
  pivot_longer(cols = `1800`:`2100`,
              names_to = 'year',
              values_to = "daily_income")
  
  
data <- clean_data1 %>% 
  inner_join(clean_data2, 
             by = join_by(country == country, year == year))


summary(data)
```

Works Cited:

Helliwell, John F., et al. \"World Happiness Report 2024.\" The World Happiness Report, 20 Mar. 2024, [worldhappiness.report/ed/2024/](http://worldhappiness.report/ed/2024/).

\"Poverty and Inequality Platform.\" Poverty and Inequality Platform, 2022, [pip.worldbank.org/#](http://pip.worldbank.org/#). 

```{r}
model <- glm(happiness ~ daily_income, data = data)
summary(model)

ggplot(data = data, mapping = aes(x = daily_income, y = happiness))+
  geom_point()+
  geom_smooth(colour = "blue")

```
